package policy

import (
	"encoding/binary"
	"math"
	"math/rand"
	"os"
	"testing"
)

// detInput builds a deterministic pseudo-random set of input blocks for a net, with k
// teammate rows and m opponent rows.
func detInput(n *Net, seed int64, k, m int) (self, ball, global, team, opp []float32) {
	r := rand.New(rand.NewSource(seed))
	fill := func(sz int) []float32 {
		s := make([]float32, sz)
		for i := range s {
			s[i] = r.Float32()*2 - 1
		}
		return s
	}
	return fill(n.SelfDim), fill(n.BallDim), fill(n.GlobalDim), fill(k * n.EntDim), fill(m * n.EntDim)
}

func TestLoadDefaultAndForward(t *testing.T) {
	n, err := LoadDefault()
	if err != nil {
		t.Fatalf("LoadDefault: %v", err)
	}
	if n.TotalHeadWidth != 34 {
		t.Errorf("TotalHeadWidth = %d, want 34", n.TotalHeadWidth)
	}
	ws := n.NewWorkspace()
	self, ball, global, team, opp := detInput(n, 7, 3, 4)
	logits := n.Forward(ws, self, ball, global, team, opp)
	if len(logits) != n.TotalHeadWidth {
		t.Fatalf("logits len = %d, want %d", len(logits), n.TotalHeadWidth)
	}
	for i, v := range logits {
		if math.IsNaN(float64(v)) || math.IsInf(float64(v), 0) {
			t.Fatalf("logit %d not finite: %v", i, v)
		}
	}
	// Empty entity groups must be handled (1v0-style rosters).
	logits0 := n.Forward(ws, self, ball, global, nil, nil)
	if len(logits0) != n.TotalHeadWidth {
		t.Fatalf("empty-roster logits len = %d", len(logits0))
	}
}

func TestBadMagicRejected(t *testing.T) {
	b := make([]byte, 64)
	copy(b, "NOTMAGIC")
	if _, err := LoadBytes(b); err == nil {
		t.Fatal("expected error for bad magic")
	}
}

func TestTruncatedRejected(t *testing.T) {
	full, err := os.ReadFile("weights/" + DefaultWeightsName)
	if err != nil {
		t.Fatalf("read weights: %v", err)
	}
	if _, err := LoadBytes(full[:len(full)-8]); err == nil {
		t.Fatal("expected error for truncated blob")
	}
}

// TestForwardGoldenVector is the Go<->Python parity gate. It is skipped until the exporter
// (training/export.py) has written testdata/golden_forward.bin. Once present, the Go forward
// pass must match the Python reference bit-for-bit (proving Go inference == the trained net).
//
// Self-describing record format (little-endian), so policy stays game-agnostic:
//
//	uint32 count
//	per record: uint32 nTeam, uint32 nOpp,
//	            float32 self[SelfDim], ball[BallDim], global[GlobalDim],
//	            float32 team[nTeam*EntDim], opp[nOpp*EntDim],
//	            float32 logits[TotalHeadWidth]
func TestForwardGoldenVector(t *testing.T) {
	const path = "testdata/golden_forward.bin"
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("no parity vectors yet (generated by training/export.py): %v", err)
	}
	n, err := LoadDefault()
	if err != nil {
		t.Fatalf("LoadDefault: %v", err)
	}
	ws := n.NewWorkspace()
	off := 0
	u32 := func() int {
		v := int(binary.LittleEndian.Uint32(raw[off:]))
		off += 4
		return v
	}
	f32n := func(k int) []float32 {
		s := make([]float32, k)
		for i := range s {
			s[i] = math.Float32frombits(binary.LittleEndian.Uint32(raw[off:]))
			off += 4
		}
		return s
	}
	count := u32()
	for c := 0; c < count; c++ {
		nTeam := u32()
		nOpp := u32()
		self := f32n(n.SelfDim)
		ball := f32n(n.BallDim)
		global := f32n(n.GlobalDim)
		team := f32n(nTeam * n.EntDim)
		opp := f32n(nOpp * n.EntDim)
		want := f32n(n.TotalHeadWidth)
		got := n.Forward(ws, self, ball, global, team, opp)
		for i := range want {
			if math.Float32bits(got[i]) != math.Float32bits(want[i]) {
				t.Fatalf("record %d logit %d: got %v (%08x) want %v (%08x)",
					c, i, got[i], math.Float32bits(got[i]), want[i], math.Float32bits(want[i]))
			}
		}
	}
}
